name: CI

on: [push]

jobs:
  build:
    name: ${{matrix.platform.name}} ${{matrix.type.name}} ${{matrix.config.name}}
    runs-on: ${{matrix.platform.os}}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows,     os: windows-latest, flags: -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$GITHUB_WORKSPACE/build/bin }
        - { name: Linux GCC,   os: ubuntu-latest }
        - { name: Linux Clang, os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS,       os: macos-latest }
        type:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }
        config:
        - { name: Debug }
        - { name: Release }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      shell: bash
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}} ${{matrix.type.flags}} -DCMAKE_BUILD_TYPE=${{matrix.config.name}}

    - name: Build
      run: cmake --build build --config ${{matrix.config.name}} --target install

    - name: Run Tests
      run: ctest --test-dir build --build-config ${{matrix.config.name}} --output-on-failure
